# Generated by Django 4.2.3 on 2023-07-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=100)),
                ("question_title", models.CharField(max_length=100)),
                ("question_text", models.TextField()),
                ("output", models.TextField()),
            ],
        ),
    ]
